server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**,/student/**,/campus_card/**
        - id: file
          uri: lb://file-service
          predicates:
            - Path=/file/**
        - id: course
          uri: lb://course-service
          predicates:
            - Path=/course/**
        - id: dormitory
          uri: lb://dormitory-service
          predicates:
            - Path=/dormitory/**
student-affairs:
  auth:
    excludePaths:
      - /user/login
      - /user/register
      - /file/**