shared-jdbc.yml:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306sudent_affairs?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    username: 
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1    # 逻辑删除的标记值（删除）
      logic-not-delete-value: 0  # 逻辑删除的标记值（未删除）
feign:
  okhttp:
    enabled: true